import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// Update metadata with keywords, author, and viewport
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  keywords: "Next.js, SEO, web development, React",
  author: "OpenXYZ",
  viewport: "width=device-width, initial-scale=1.0",
};

function ErrorBoundary({ children }: { children: React.ReactNode }) {
  return (
    <ErrorBoundaryComponent>
      {children}
    </ErrorBoundaryComponent>
  );
}

function ErrorBoundaryComponent({ children }: { children: React.ReactNode }) {
  return (
    <div role="alert">
      {children}
    </div>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="keywords" content="Next.js, SEO, web development, React" />
        <meta name="author" content="Your Name" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className={inter.className}>
        <ErrorBoundary>
          {children}
        </ErrorBoundary>
      </body>
    </html>
  );
}
